<?php

namespace App\Constants;

return [
    'ABOUT_US_IMAGE_MAX_SIZE'=>'2048',
    'ABOUT_US_IMAGE_MIN_SIZE'=>'10',

    'HOME_IMAGE_MAX_SIZE'=>'10240',
    'HOME_IMAGE_MIN_SIZE'=>'10',

    'TRESS_IMAGE_MAX_SIZE'=>'2048',
    'TRESS_IMAGE_MIN_SIZE'=>'10',

    'AUDIO_MAX_SIZE'=>'5120',
    'AUDIO_MIN_SIZE'=>'10',

    'VIDEO_MAX_SIZE'=>'51200',
    'VIDEO_MIN_SIZE'=>'10',

    'FLOWERS_IMAGE_MAX_SIZE'=>'2048',
    'FLOWERS_IMAGE_MIN_SIZE'=>'10',

    
    'ZONE_AREA_IMAGE_MAX_SIZE'=>'2048',
    'ZONE_AREA_IMAGE_MIN_SIZE'=>'10',

    'AMENITIES_IMAGE_MAX_SIZE'=>'2048',
    'AMENITIES_IMAGE_MIN_SIZE'=>'10',

    'GALLERY_IMAGE_MAX_SIZE'=>'2048',
    'GALLERY_IMAGE_MIN_SIZE'=>'10',

    'ICON_MASTER_IMAGE_MAX_SIZE'=>'1024',
    'ICON_MASTER_IMAGE_MIN_SIZE'=>'1',
    
];